name: snowexhack21
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - cartopy
  - rasterio
  - python=3.7
  - gdal
  - ipykernel
  - pyepsg
  - ipympl
  - nodejs
  - scikit-learn
  - jupyterlab
  - fiona
  - requests

  - pip:
      - git+git://github.com/SnowEx/snowexsql/
      - git+git://github.com/mjsandells/snowmicropyn
prefix: /Users/siegfried/opt/anaconda3/envs/gpgn314
